project:
  type: website

website:
  title: "CSI Math"
  favicon: images/favicons/wavelet.svg
  bread-crumbs: true
  sidebar:
    - title: People
      contents: People
    - title: Undergraduate
      contents: Undergraduate
    - title: ADA Compliance
      contents: ADA
##
  navbar:
    background: $csi-blue
    pinned: true
    collapse-below: "md"
    logo: images/favicons/wavelet.svg
    logo-alt: "CSI Math"
    left:
      - text: "About"
        href: about.qmd
      - text: "Jobs"
        href: jobs.qmd
      - text: "People"
        menu:
          - People/faculty/index.qmd
          - People/staff/index.qmd
      - text: "Undergraduate"
        href: Undergraduate/index.qmd
      - text: "Courses"
        href: Undergraduate/Courses/course_list.qmd
      - text: TEHA
        href: https://www.csi.cuny.edu/academics-and-research/specialized-programs/honors-programs/teacher-education-honors-academy
      - text: Syllabi
        href: Undergraduate/Courses/Syllabi/index.qmd
##
  announcement:
    icon: newspaper
    dismissable: true
    content: |
      Welcome back for the Fall!
      <span style="color: purple;">**Please note: default WeBWorK usernames/passwords are now your student ID numbers**</span>
      (*just the number*)!
      Please change your password after you first log in.
    type: primary
    position: below-navbar
  page-footer:
    left:
      - text: |
          <img src="/images/square/CUNY_Logo-32-32.png" alt="">
      - text: City University of New York
        href: https://www.cuny.edu
      - text: College of Staten Island
        href: https://www.csi.cuny.edu
    center: |
      <i class="bi bi-telephone"></i> 718-982-3600
      <i class="bi bi-envelope"></i> [mathematics@csi.cuny.edu](mailto:mathematics@csi.cuny.edu)
      <br>
      <i class="bi bi-geo"></i> [1S-215; 2800 Victory Blvd., Staten Island, NY, 10314](https://maps.app.goo.gl/56hLqe2EDDuubxAE6)

format:
  html:
    theme:
      - cosmo
      - csi-math.scss
    mainfont: Raleway
    grid:
      body-width: 1200px
    toc: false
    css: "https://cdn.jsdelivr.net/gh/ryersondmp/sa11y@4.0.5/dist/css/sa11y.min.css"
    include-in-header:
    - text: |
       <script src="https://cdn.jsdelivr.net/combine/gh/ryersondmp/sa11y@4.0.5/dist/js/lang/en.umd.js,gh/ryersondmp/sa11y@4.0.5/dist/js/sa11y.umd.min.js"></script>
    include-before-body:
    - text: |
        <script>
          Sa11y.Lang.addI18n(Sa11yLangEn.strings);
          const sa11y = new Sa11y.Sa11y({
            checkRoot: "body",
          });
        </script>
