#=
Script to generate links. We have headers.
Could be used again, as not quite right yet
::::: {.card}
:::: {.card-header}
Course links
::::
=#


using Mustache
using Markdown

course_links = [
(NM="WeBWorK",
 URL="/WeBWorK/courses.html",
 ALT="webwork",
 BI="pencil"),

(NM="WebAssign",
 URL="https://www.webassign.net/",
 ALT="webassign",
 BI="pencil"),

(NM="MyStatLab",
 URL="https://mlm.pearson.com/northamerica/mystatlab/",
 ALT="mystatlab",
 BI="pencil"),

(NM="JuliaBox",
 URL="/juliabox",
 ALT="JuliaBox",
 BI="terminal-fill"),

(NM="Course Materials",
 URL="/Undergraduate/Courses/",
 ALT="Materials",
 BI="pencil"),

(NM="Tutoring",
 URL="/Undergraduate/Tutoring/",
 ALT="Tutoring",
 BI="person-circle")
]

quick_links = [
	(NM="Brightspace",
	 URL="https://brightspace.cuny.edu/",
	 ALT="brightspace",
	 BI="journal"),

	(NM="BlackBoard",
	 URL="https://www.cuny.edu/about/administration/offices/cis/core-functions/cuny-blackboard/",
	 ALT="blackboard",
	 BI="journal"),

	(NM="CUNYFirst",
	 URL="https://www.cuny.edu/about/administration/offices/cis/cunyfirst/",
	 ALT="cuny first",
	 BI="tools"),

	(NM="Navigate",
	 URL="https://csi-cuny.campus.eab.com/",
	 ALT="Navigate",
	 BI="tools"),

	(NM="Math major",
	 URL="/Undergraduate/Major/",
	 ALT="Major",
	 BI="ui-checks-grid"),

	(NM="Mathclub",
	 URL="https://math-csi-cuny.github.io/mathclub/",
	 ALT="Major",
	 BI="transparency"),

	(NM="Advisement",
	 URL="/Undergraduate/AdvisingDocuments/",
	 ALT="Advisement",
	 BI="person-check-fill"),

	(NM="Careers",
	 URL="/Undergraduate/Career/",
	 ALT="Careers in mathematics",
	 BI="door-open"),

    (NM="Teacher Education Honors Academy",
     URL="https://www.csi.cuny.edu/academics-and-research/specialized-programs/honors-programs/teacher-education-honors-academy",
     ALT="Teacher Education Honors Academy",
     BI="lightbulb"),

	(NM="Course schedule",
	 URL="/Undergraduate/Courses/CUNYFirst/",
	 ALT="Course Schedule",
	 BI="layout-wtf"),

	(NM="Calendar",
	 URL="/calendar.html",
	 ALT="College calendar",
	 BI="calendar-week"),

	(NM="Accessibility",
	 URL="https://mth229.github.io/CSI-Math-ADA/",
	 ALT="Accessibility",
	 BI="pencil"),

	(NM="Transition to Bright Space",
	 URL="/BB2BS/",
	 ALT="Brightspace",
	 BI="pencil"),

]

tpl = mt"""
:::: {.nav  .flex-column}
{{#:SIDEBAR}}
[<i class="bi bi-{{:BI}}"></i> {{{:NM}}}]({{{:URL}}}){.nav-link .text-black}
{{/:SIDEBAR}}
::::
"""
#=
tpl = mt"""
:::: {.d-grid .gap-1}
{{#:SIDEBAR}}
::::: {.btn .btn-light}
<i class="bi-{{:BI}}"></i>
[{{:NM}}]({{{:URL}}}){.btn-outline-light alt="{{:ALT}}"}
:::::

{{/:SIDEBAR}}
::::
"""


otpl = mt"""
<div class="d-grid gap-0 col-6 mx-auto">
{{#:SIDEBAR}}
<button class="btn btn-outline-light btn-block" type="button">
<a href="{{{:URL}}}"  class="nav-link text-black" aria-current="page">
<i class="bi bi-{{:BI}}"></i>
<abbrv aria-details="{{:NM}}" title="{{:NM}}" alt="{{:ALT}}">
{{:NM}}
</abbrv>
</a>
</button>
{{/:SIDEBAR}}
</div>
"""

atpl = mt"""
<ul class="nav nav-pills flex-column mb-auto">
{{#:SIDEBAR}}
    <li class="nav-item">
<a href="{{{:URL}}}"  class="nav-link text-black" aria-current="page">
<i class="bi bi-{{:BI}}"></i>
<abbrv aria-details="{{:NM}}" title="{{:NM}}" alt="{{:ALT}}">
{{:NM}}
</abbrv>
</a>
</li>
{{/:SIDEBAR}}
</ul>

"""
=#

file = "sidebar.qmd"
open(file,"w") do io
    println(io, "<!-- autogenerated by `julia sidebar-links.jl` -->")
    println(io, """
::: {.d-grid .gap-0}
:::: {.card}
::::: {.card-header}
Class links
:::::
""")

    Mustache.render(io, tpl; SIDEBAR=course_links)

    println(io, """
::::
:::

::: {.d-grid .gap-0}
:::: {.card}

::::: {.card-header}
Quick links
:::::
""")

    Mustache.render(io, tpl; SIDEBAR=quick_links)

    println(io, """
::::
:::
""")
end
