# run as `julia sidebar-links.jl`

using Mustache
using Markdown

function (@main)(args)
    file = "sidebar.qmd" # write here

    # adjust here
    # both course links and quick links
    course_links = [
        (NM="WeBWorK",
         URL="/WeBWorK/courses.html",
         ALT="webwork",
         BI="pencil"),

        (NM="WebAssign",
         URL="https://www.webassign.net/",
         ALT="webassign",
         BI="pencil"),

        (NM="MyStatLab",
         URL="https://mlm.pearson.com/northamerica/mystatlab/",
         ALT="mystatlab",
         BI="pencil"),

        (NM="JuliaBox",
         URL="/juliabox",
         ALT="JuliaBox",
         BI="terminal-fill"),

        (NM="Course Materials",
         URL="/Undergraduate/Courses/",
         ALT="Materials",
         BI="pencil"),

        (NM="Tutoring",
         URL="/Undergraduate/Tutoring/",
         ALT="Tutoring",
         BI="person-circle")
    ]

    quick_links = [
	(NM="Brightspace",
	 URL="https://brightspace.cuny.edu/",
	 ALT="brightspace",
	 BI="journal"),

	(NM="CUNYFirst",
	 URL="https://www.cuny.edu/about/administration/offices/cis/cunyfirst/",
	 ALT="cuny first",
	 BI="tools"),

	(NM="Navigate",
	 URL="https://csi-cuny.campus.eab.com/",
	 ALT="Navigate",
	 BI="tools"),

	(NM="Math major",
	 URL="/Undergraduate/Major/",
	 ALT="Major",
	 BI="ui-checks-grid"),

	(NM="Mathclub",
	 URL="https://math-csi-cuny.github.io/mathclub/",
	 ALT="Major",
	 BI="transparency"),

	(NM="Advisement",
	 URL="/Undergraduate/AdvisingDocuments/",
	 ALT="Advisement",
	 BI="person-check-fill"),

	(NM="Careers",
	 URL="/Undergraduate/Career/",
	 ALT="Careers in mathematics",
	 BI="door-open"),

        (NM="Teacher Education Honors Academy",
         URL="https://www.csi.cuny.edu/academics-and-research/specialized-programs/honors-programs/teacher-education-honors-academy",
         ALT="Teacher Education Honors Academy",
         BI="lightbulb"),

	(NM="Course schedule",
	 URL="/Undergraduate/Courses/CUNYFirst/",
	 ALT="Course Schedule",
	 BI="layout-wtf"),

	(NM="Calendar",
	 URL="/calendar.html",
	 ALT="College calendar",
	 BI="calendar-week"),

	(NM="Accessibility",
	 URL="ADA",
	 ALT="Accessibility",
	 BI="pencil"),

	(NM="Transition to Bright Space",
	 URL="/BB2BS/",
	 ALT="Brightspace",
	 BI="pencil"),

]

#
#

    nav_link_tpl = mt"""
:::: {.nav  .flex-column aria-current="page"}
{{#:SIDEBAR}}
::::: {.btn .btn-light .text-start .px-0 .mx-0 .py-0 .my-0}
[<i class="bi bi-{{:BI}}"></i> {{{:NM}}}]({{{:URL}}}){.nav-link .nav-fill .table-hover .text-black}
:::::
{{/:SIDEBAR}}
::::
"""

#    style="cursor:pointer;"
    button_tpl = mt"""
{{#:SIDEBAR}}
::::: {.btn .btn-light .text-start .text-black}
[<i class="bi-{{:BI}}"></i> {{:NM}}]({{{:URL}}}){.btn-outline-light alt="{{:ALT}}"}
:::::

{{/:SIDEBAR}}
"""

tpl = nav_link_tpl

    page_tpl = """
<!-- autogenerated by julia sidebar-links.jl -->

::: {.d-grid .gap-0}
:::: {.card}
::::: {.card-header}
Class links
:::::

{{{:CLASS}}}

::::
:::

::: {.d-grid .gap-0}
:::: {.card}

::::: {.card-header}
Quick links
:::::

{{{:QUICK}}}

::::
:::
"""

    CLASS = Mustache.render(tpl; SIDEBAR=course_links)
    QUICK = Mustache.render(tpl; SIDEBAR=quick_links)

    open(file, "w") do io
        Mustache.render(io, page_tpl; CLASS, QUICK)
    end
end
