# Notes on LaTeX

::: {.callout-note}
The support of tagged PDF within \LaTeX is ongoing. The most up-to-date report
is [available here][1] (direct link to [2024 PDF][2]).

The Overleaf team also has an [extensive document][3] on this topic; while they
don't give many concrete suggestions for authors, they do provide a lot of info
about the challenges and explanations of the internals and PDF standards.

We value any testing for the advice on this page. Please open a [Github
issue](https://github.com/collegeofstatenislandmath/collegeofstatenislandmath.github.io/issues)
if you have suggestions.
:::

> Because LaTeX was designed as a typesetting program, PDF documents created using LaTeX do not include the document structure and tagging required for accessibility by default. It is possible to create accessible PDF documents using LaTeX but users will need to use additional LaTeX packages and should be aware of accessibility standards. The Accessibility package in LaTeX can be used to add the structure, tagging, and alt text that PDF's created with LaTeX lack.
>
> From [LaTeX Guides](https://libguides.lib.msu.edu/c.php?g=995742&p=8207771)


Here is a sample preamble with additions for accessibility:
```tex
\DocumentMetadata{
    testphase=phase-III, % enables tagging
    pdfstandard=A-2b     % declares that the pdf supports the A-2b standard
                         % note: this is only metadata, it does not enforce
                         % nor test anything
}
\documentclass{article}     % unclear if amsart is supported, needs more testing
\usepackage[utf8]{inputenc} % unrelated to accessibility
\usepackage{hyperref}

\hypersetup{
    pdflang=en-US,
    pdftitle={<title of PDF>},
    pdfauthor={<author>}
}
```

::: {.callout-note}
Documentation for supported key/values for `\DocumentMetadata` [is given here](https://texdoc.org/serve/documentmetadata-support/0).
:::

## Additional recommendations:

* Use the most up-to-date version of LuaLaTeX/PDFLaTeX available.
* LuaLaTeX or PDFLaTeX support tagging, other engines (e.g. XeTeX) are untested and may not work
* As with HTML, you should write your document using structured tags (`\section`, `\subsection`) so that these can be communicated to e-readers.
* Likewise, pictures should include alt-text, e.g. `\includegraphic[alt={Rubber Duck}]{ducky.jpg}`
* There is also an early prototype for tagging formulas. Use `\DocumentMetadata{testphase={phase-III,math}}` to load.
* See the [LaTeX project's report][1] for full details


## Further reading

Some links of interest (re: accessible LaTeX):

* [https://www.ams.org/journals/notices/202301/rnoti-p68.pdf](https://www.ams.org/journals/notices/202301/rnoti-p68.pdf)

* [https://libguides.lib.msu.edu/c.php?g=995742&p=8207771](https://libguides.lib.msu.edu/c.php?g=995742&p=8207771)

* [https://tex.stackexchange.com/questions/261537/a-guide-on-how-to-produce-accessible-pdf-files](https://tex.stackexchange.com/questions/261537/a-guide-on-how-to-produce-accessible-pdf-files)

* [PDF-A Compliant LaTeX](https://shen.hong.io/reproducible-pdfa-compliant-latex/)

[1]: https://www.latex-project.org/publications/indexbytopic/pdf/
[2]: https://www.latex-project.org/publications/2024-FMi-DPC-UFi-JAW-doceng24.pdf
[3]: https://www.overleaf.com/learn/latex/An_introduction_to_tagged_PDF_files%3A_internals_and_the_challenges_of_accessibility#Introducing_tagged_PDF
