# Notes on Quarto

[Quarto](https://quarto.org/) is an open-source scientific and technical publishing system which can be used to publish in HTML, PDF, and other formats. A key feature is easy integration with programming languages like Julia, R, and Python.


## Quarto can use different tools,

It appears that $\LaTeX$ will evolve to have more support for tagging of PDF documents. See [tagpdf](https://ctan.org/pkg/tagpdf?lang=en) for some details.

The `tinytex` installation is very current. The name implies it is small, but how? It downloads packages on demand, so unlike other TeX installations, you need not have everything on your hard drive.

To install `tinytex` is [easy](https://quarto.org/docs/output-formats/pdf-engine.html)

> `quarto install tinytex`

As an aside, there are `quarto update tinytex` and `quarto uninstall tinytex` commands.

::: {.callout-warning}
## Quarto heads up
PDFs produced by Quarto are not tagged and when last tested, no success was
found in trying to implement the advice from the [latex page](latex.qmd).

It's possible that this changes as changes are made to Pandoc, but until then,
when accessibility is a must, it is recommended to provide both HTML and PDF
output.

[1]: https://github.com/jgm/pandoc/issues/5409
[2]: https://pandoc.org/MANUAL#accessible-pdfs-and-pdf-archiving-standards
:::
