---
title: Major/Minor requirements and sample schedules
order: 2
---

## General info

- For advisement please send request to [mathadvisor@csi.cuny.edu](mailto:mathadvisor@csi.cuny.edu)
- [Helpful Advising Links](00-Advising links.pdf)

## B.S. in Math

-   Degree Requirements for
    [B.S. in Mathematics](Degree_Req_BS_in_Math_Fall2024.pdf)
    and Gen Ed [recommended courses.](Math_GenEd.pdf)
-   Eight semester sample schedule (Math)
    [starting with Calculus.](MathematicsBS_DegreeMap.pdf)

## B.S. in Math (7-12 education)

-   Degree Requirements for B.S. in
    [Mathematics (7-12 ed.)](Degree_Req_BS_in_MathEd_Fall2024.pdf)
    and Gen Ed [recommended courses](MathEd_GenEd.pdf)
-   Eight semester sample schedule
    [(Math-Ed) starting with Calculus](Mathematics7-12BS_DegreeMap.pdf).
-   Schedule for [Undergraduate EDS sequence](UG_Sec_Program_MthED_NOT_TEACHER_ACADEMY_EDS_sequence.pdf)

## B.S. in Computer Science/Math

-   Degree Requirements for B.S. in
    [Computer Science Math](degree_Req_BS_in_CS_Math_Fall2024.pdf)
    and Gen Ed [Recommended Courses](MthCSC_GenEd_Veronica.pdf)
-   Eight semester sample schedule (Computer Sci-Math)
    [starting with Calculus.](ComputerScienceMathematicsBS_DegreeMap.pdf)

## Mathematics Minor

Revised requirements for Fall 2025:

**Complete the following courses with a minimum GPA of 2.0 in these courses:**

* MTH 229
* MTH 230 or MTH 231
* MTH 232
* MTH 233
* MTH 338
* Two other 300 or 400 level mathematics courses, at least one of which is not used to satisfy any other major or minor requirements.

**For the Mathematics Minor, three 300 or 400 level mathematics courses must be taken at CSI.**

## Data Science Minor (Math/CS)

[Requirements:](https://csi-undergraduate.catalog.cuny.edu/programs/DATASC-MIN)

**Fulfill ALL of the following requirements:**

**Complete ALL of the following Courses:**

* CSC 245 - Introduction to Data Science
* MTH 311 - Probability Theory and an Introduction to Mathematical Statistics

**Complete at least 1 of the following Courses:**

* CSC 412 - Machine Learning and Knowledge Discovery
* MTH 372 - Practical Machine Learning

**Complete at least 1 of the following Courses:**

* CSC 315 - Introduction to Database Systems
* CSC 412 - Machine Learning and Knowledge Discovery
OR MTH 372 - Practical Machine Learning
* CSC 480 - Artificial Intelligence
* MTH 410 - Mathematical Statistics I

**Complete at least 1 of the following Courses:**

* CSC 594 - Comp Sci Ind Study
* MTH 594 - Math Ind Study
