---
title: Mathematics departments in the vicinity of the College of Staten Island.
---

The College of Staten Island is centrally located with respect to the
New York area mathematics research community. In addition to 7 world
class university centers, there are nearly 100 nearby colleges.
Moreover, the number of industrial mathematicians in the area is
staggering.

There are regular seminars at the following major research centers

-   [CUNY Graduate Center](http://math.gc.cuny.edu/) (36 minutes drive
    time from CSI)
-   [Rutgers University](http://www.math.rutgers.edu/), including
    [DIMACS](http://dimacs.rutgers.edu/) (25 minutes away)
-   [Courant Institute/New York University](http://math.nyu.edu/) (31
    minutes away)
-   [Columbia University](http://www.math.columbia.edu/) (45 minutes
    away)
-   [Princeton University](http://www.math.princeton.edu/) (52 minutes
    away)
-   [Institute for Advanced Study](http://www.math.ias.edu/) (55 minutes
    away)
-   [SUNY Stony Brook](http://www.math.sunysb.edu/html/index.shtml) (95
    minutes away)

There are nearly 100 additional nearby colleges, and dozens of
substantial industry-sponsored research groups in the area. Below is a
very incomplete list.

-   [Wagner College](http://www.wagner.edu/departments/math/home) (9
    minutes)
-   [Montclair State
    University](http://csam.montclair.edu/mathsci/mathsci.html) (38
    minutes)
-   (CUNY) [Lehman College](http://comet.lehman.cuny.edu/mathdept/) (44
    minutes)
-   (CUNY) [Hunter College](http://math.hunter.cuny.edu/) (41 minutes)
-   (CUNY) [New York City College of
    Technology](http://www.citytech.cuny.edu/academics/deptsites/mathematics/)
    (23 minutes)
-   (CUNY) [Baruch](http://www.baruch.cuny.edu/math/index.html) (36
    minutes)
-   [The Cooper
    Union](http://www.cooper.edu/engineering/departments.html#math) (30
    minutes)
-   [Fordham University](http://www.fordham.edu/mathematics/) (47
    minutes)

This list is dramatically incomplete, and the maintainer (obryant at
gmail dot com) would appreciate any additions. The criteria is that the
school must be accredited and must have a faculty member with
mathematics publications. Drive times were generated by Google maps, and
do not account for public transportation, traffic, construction, et
cetera.
