---
title: Learning goals for MTH329
order: 329
---

## Role in Curriculum

This course gives math majors a background to a body of mathematics
beyond that offered by the
required math courses. This course is an elective for all math majors,
but is required for math
majors with a specialization in adolescent education

## Learning Goals and Assessment Plans

> The student will use Euclidean axioms,
> coordinates, vectors, and/or transformations to
> verify a given geometric result.

When the class is being assessed, the final exams
will include embedded questions to assess student
performance on these topic-specific learning
goals. Instructors are responsible for tallying
their students scores.

> The student will prove a given geometric
> statement by writing a concise but complete
> mathematical argument

same

> The student will use compass and straightedge to
> perform a given Euclidean construction.

same

> The student will be familiar with a geometry that
> does not satisfy all Euclidean axioms.

same

----

When assessment activities are done, the results will be summarized in
memorandum form and filed with the department chairperson for record
keeping
purposes.

Information obtained from assessment will be used to assess and
self-reflect on the success of the course and to make any necessary
changes to
improve teaching and learning effectiveness.

------------------------------------------------------------------------

Last updated Mon May 24 14:48:07 2010
