---
title: Learning goals for MTH218
order: 218
---

## Role in Curriculum

Enhancing the prospective teacher's understanding of fundamental
concepts for the instruction of
geometry and statistical concepts

## Learning Goals and Assessment Plans

> The student will be able to understand and
> explain the geometric properties of and
> relationships between various types of polygons,
> with special emphasis on triangles and
> quadrilaterals.

When the class is being assessed, the final exams
will include embedded questions to assess student
performance on these topic-specific learning
goals. Instructors are responsible for tallying
their students scores.

> The student will be able to find the area of a
> given geometric shape through its decomposition
> into simpler shapes such as triangles and
> rectangles. The student will be able to find the
> volume of simple geometric solids.

same

> The student will be able to perform conversions
> within and between various English and metric
> units of length, area, and volume.

same

> The student will be able to read, understand and
> construct the visual representation of data and
> exhibit an understanding of the mean, median, and
> mode.

same

----

When assessment activities are done, the results will be summarized in
memorandum form and filed with the department chairperson for record
keeping
purposes.

Information obtained from assessment will be used to assess and
self-reflect on the success of the course and to make any necessary
changes to
improve teaching and learning effectiveness.

------------------------------------------------------------------------

Last updated Mon May 24 14:48:07 2010
