---
title: Learning goals for MTH123
---

## Role in Curriculum

MTH 123 is a college algebra / trigonometry class that provides
mathematical skills necessary for
further success in STEM (science, technology, engineering and
mathematics), business and teaching
majors. It satisfies the general education requirement. Moreover, MTH
123 prepares the students for
the next level of courses in mathematics, usually pre-calculus. The
prerequisite is MTH 030 or an
appropriate score on the CUNY proficiency/placement exam taken by many
students who stop at Regents
A

## Learning Goals and Assessment Plans


> Solve equations and manipulate expressions with
> linear, quadratic, exponential, logarithmic and
> trigonometric functions.

When the class is being assessed, the final exams
will include embedded questions to assess student
performance on these topic-specific learning
goals. Instructors will tally their students'
scores on these questions, and will forward this
data to the chair of the department pre-major
curriculum committee

> Analyze graphs of linear, quadratic, exponential,
> logarithmic and trigonometric functions.

same

> Solve application problems using these functions.

same

----

When assessment activities are done, the results will be summarized in
memorandum form and filed with the department chairperson for record
keeping
purposes.

Information obtained from assessment will be used to assess and
self-reflect on the success of the course and to make any necessary
changes to
improve teaching and learning effectiveness.

------------------------------------------------------------------------

Last updated Mon May 24 14:48:07 2010
