---
title: Graduation and Departmental Awards
order: 5
---

The **Graduation Awards** are given to our most outstanding graduates for that year.  The **Departmental Awards** are given to
outstanding students in their Sophomore or Junior years.

#### 2023

- **Graduation Awards**
    * Mitchel Kharnak
    * John Gambale
    * Janet Akselrud
    * Melissa Sorrentino
    * Frederick Spreen

- **Departmental Awards**
    * Kenny Feng
    * Jad Ibrahim
    * Megan Trapanese

#### 2022

- **Graduation Awards**
    * Amal Abdelaziz
    * Stivi Manoku
    * Jesse Dimino
    * Vincent Ndokaj

- **Departmental Awards**
    * John Galindo
    * Laura Kaplan
    * Mathew Keeler
    * Bhavya Premachandran

#### 2021

- **Graduation Awards**
    * Chukwurado Umeaka
    * Justin Peterkin
    * Joshua Higgins

- **Departmental Awards**
    * Stivi Manoku
    * Sierra Arcuri
    * Jenna Calderon
    * Jesse Dimino

#### 2020

- **Graduation Awards**
    * Dajana Avxhi
    * Serena Newman
    * Mitchel Weitzman

- **Departmental Awards**
    * Ilmi Demirovic
    * Joshua Higgins
    * Chinedu Okoye

#### 2019

- **Graduation Awards**
    * Nicholas Veneziano
    * Nicholas Borghese
    * Jing Gian

- **Departmental Awards**
   * Dajana Avxhi
   * Chukwurado Umeaka
   * Mitchell Weitzman
   * Jinglin Ye

#### 2018

- **Graduation Awards**
    * Robert Ferrando
    * Rayan Ibrahime
    * Concetta Perito
    * Irteza Syed

- **Departmental Awards**
    * Rocco Fama
    * Nicholas Veneziano

#### 2017

- **Graduation Awards**
    * Christopher Pinto
    * Timothy Sweeney
    * Heather Mak
    * Sarah Sietz

- **Departmental Awards**
    * Jing Gian
    * Brandon Lei
    * Serena Newman
    * Concetta Perito

#### 2016

- **Graduation Awards**
    * Keith Thompson
    * Bassem Nawar
    * Quixia Yang
    * Lilani Seneviratne

- **Departmental Awards**
    * Robert Ferrando
    * Sarah Sietz

#### 2015

- **Graduation Awards**
    * Argenta Benis
    * Danielle Auriti
    * Lydia Chung
    * Angelo Rago
    * Justin Van Wygerden

- **Departmental Awards**
    * Bassem Nawar
    * Keith Thompson
    * Michelle Vann
    * Qiuxia Yang

#### 2014
- **Graduation Awards**
    * Scott Edkins
    * Ying Yu
    * Jenna Theuret
    * Suzanne Frank
    * Itiel Cohen (Student Government Award)

- **Departmental Awards**
    * Argenta Benis
    * Lydia Chung
    * Suada Hilili
    * Linani Sereviratne


#### 2013
- **Graduation Awards**
    * Anthony DeLuca
    * Andrea Cella
    * Michel Abdo
    * Elena Sverdlova
    * Angelo Rago

- **Departmental Awards**
    * Scott Edkins
    * Suzanne Frank
    * William George
    * Antonio Grasso

#### 2012

- **Graduation Awards**
    * Daniel Kurzweil
    * Jaclyn Marzella
    * Sylvanna Salama
    * Annelise Kropp
    * Katherine Stone

- **Departmental Awards**
    * Ying Yu
    * Danielle Aruti

#### 2011

- **Graduation Awards**
    * Anna Theodoropoulos
    * Ensela Mema
    * Ilirjana Duka
    * Raechel Strobel

- **Departmental Awards**
    * Elena Sverdlova
    * Anthony DeLuca
    * Andrea Cella

#### 2010

- **Graduation Awards**
    * Bernard Adamitey
    * Jonathan Maltz
    * Mouwafak Abbas
    * Marilyn Schulz

- **Departmental Awards**
    * Jenna Theuret
    * Cynthia Murillo
    * Annelise Kropp
    * Christine Rivera

#### 2009

- **Graduation Awards**
    * Ismael Yacabou Djima
    * Tony Ramirez
    * Joseph Zancocchio
    * Arti Mela

- **Departmental Awards**
    * Sylvana Salama
    * Timothy Mullen
    * Daniel Kurzweil

#### 2008

- **Graduation Awards**
    * Karamatou Yacoubou Djima
    * Deena Thengone
    * Vadim Plaxine


Graduation Awards have included:

**The Louis Blake Memorial Award** is awarded by the faculty of the
Mathematics Department to an outstanding graduating student in
memory of Louis Blake, a member of the Mathematics Department
from 1975 to 1985.

**The Sherry Blackman Memorial Award** is awarded by the faculty of
the Mathematics Department to an outstanding graduating student in
memory of Sherry Blackman, a member of the Mathematics
Department from 1970 to 2007.

**The CSI Auxiliary Services Corporation Award** for Academic
Excellence in Mathematics is awarded by the faculty to an
outstanding graduating student.

**Benedict Carlat Memorial Award** for Outstanding Work in
Mathematics.  Awarded to an outstanding graduating mathematics major
selected by the faculty of the Mathematics Department. The award,
established by the Carlat family, honors the memory of Benedict
Carlat, a member of the Mathematics Department from 1962 to 1976,
chairperson from 1968 to 1976, and who taught the first computer
course at CSI.
