---
title: Learning goals for MTH121
---

## Role in Curriculum

Introductory mathematics course for business and economics

## Learning Goals and Assessment Plans


> The student will be able to understand the concept of a function, find its domain,solving linear and quadratic equations and inequalities.

When the class is being assessed, the final exams will include embedded
questions to assess student performance on these topic-specific learning
goals. Instructors will tally their students' scores on these
questions, and will forward this data to the chair of the department
pre-major curriculum committee

> The student will learn to solve applied problems like finding minimum or maximum of a quadratic function, problems involve interest rate calculations.

same

> The student will learn the concepts of exponential and logarithmic functions and solve simple exponential and logarithmic equations.

same

When assessment activities are done, the results will be summarized in
memorandum form and filed with the department chairperson for record
keeping purposes.

Information obtained from assessment will be used to assess and
self-reflect on the success of the course and to make any necessary
changes to improve teaching and learning effectiveness.
