---
title: Undergraduate
---

The Department of Mathematics has around 70 declared majors at any given time and offers around 100 courses each semester for the students of the college.

----

## For Current Students

- [Program requirements and sample schedules](AdvisingDocuments/)
- [Program and Course Description](Major/)
- [Courses and accompanying materials](Courses)
- [Tutoring in Mathematics at CSI](Tutoring)
- [Independent study courses (MTH594)](independent-study.qmd)
- [Advising documents](advising-resources.qmd)

## Opportunities & Resources

- [Career opportunities](Career)
- [Simons Undergraduate Lecture Series](simons-undergraduate-lecture-series/)
- [Math Department Awards](Awards/)
- [Honors Theses](HonorsTheses/)
- [Alumni](Alumni)

## College Resources

- [CSI Major Exploration Tools](https://www.csi.cuny.edu/students/academic-advisement/students/major-exploration-tools)
- [The Teacher Academy](http://www.csi.cuny.edu/teacheracademy)   
- [The Math Club](https://math-csi-cuny.github.io/mathclub)