---
title: Learning goals for MTH130
---

## Role in Curriculum

MTH 130 is a pre-calculus class that provides mathematical skills
necessary for calculus. Students
may instead take MTH 230, which includes the material in both MTH 130
and MTH 231

## Learning Goals and Assessment Plans


> Solve equations and manipulate expressions with
> trigonometric, inverse trigonometric, polynomial
> and rational functions.

When the class is being assessed, the final exams
will include embedded questions to assess student
performance on these topic-specific learning
goals. Instructors will tally their students'
scores on these questions, and will forward this
data to the chair of the department pre-major
curriculum committee

> Analyze graphs of trigonometric, inverse
> trigonometric, polynomial and rational functions.

same

> Solve application problems using these functions.

same

----

When assessment activities are done, the results will be summarized in
memorandum form and filed with the department chairperson for record
keeping
purposes.

Information obtained from assessment will be used to assess and
self-reflect on the success of the course and to make any necessary
changes to
improve teaching and learning effectiveness.

------------------------------------------------------------------------

Last updated Mon May 24 14:48:07 2010
