---
title: Learning goals for MTH217
---

## Role in Curriculum

Enhancing the prospective teacher's understanding of fundamental
concepts for the instruction of
arithmetic

## Learning Goals and Assessment Plans

Learning Goal

Assessment

> Students will be able to perform the standard
> algorithms for arithmetic operations and explain
> the meaning behind them.

When the class is being assessed, the final exams
will include embedded questions to assess student
performance on these topic-specific learning
goals. Instructors are resposible for tallying
their students scores.

> Students will be able to identify incorrect
> procedures and the misconceptions that lead to
> them. They will be able to recognize and explain
> why a solution is reasonable.

same

> Students will be able to perform these operations
> using a variety of illustrative methods involving
> visual representations and diagrams.

same

> Students will be able to solve and create a wide
> variety of word problems relevant to each of the
> topics covered throughout the course.

same

----

When assessment activities are done, the results will be summarized in
memorandum form and filed with the department chairperson for record
keeping
purposes.

Information obtained from assessment will be used to assess and
self-reflect on the success of the course and to make any necessary
changes to
improve teaching and learning effectiveness.

------------------------------------------------------------------------

Last updated Mon May 24 14:48:07 2010
