---
title: WeBWorK Resources
order: 998
---

- Find WebWork links for specific math courses here: [WeBWorK Courses](/WeBWorK/courses.html)

- Read [How to Enter Answers in WeBWorK](./HowToEnterAnswersInWeBWorK.pdf) to learn how to enter expressions, symbols, functions, etc.

::: {.callout-note}
## To gain access to lab computers on campus:

See [helpdesk](https://www.csi.cuny.edu/sites/default/files/pdf/studenthelpdesk/hd_authenticationlab.pdf)
for information.

:::

- For instructors: [how to link WeBWorK to Brightspace](https://www.maher.org.uk/~math/webworks/)
    - This will automatically create accounts for students when they click the
    Brightspace link. Their username will be their CUNY login
    (firstname.lastname##) and they can set a password to enable them to login
    without having to first go through Brightspace.
    - Note: in the third step, if no Context ID is shown, wait a bit and try again. I ran into this issue and it resolved on its own the next time I logged into Brightspace.
